stock/urls.py
from django.urls import path

from . import views

app_name = 'stock'
urlpatterns = [
    path('', views.TickerList.as_view(), name='ticker_list'),
    path('<str:ticker_pk>', views.ticker_prices, name='ticker_prices'),
    path('<str:ticker_pk>/analytics', views.ticker_analitycs, name='ticker_analytics'),
    path('<str:ticker_pk>/delta', views.ticker_delta, name='ticker_delta'),
    path('<str:ticker_pk>/insider', views.ticker_transactions, name='ticker_insider'),
    path('<str:ticker_pk>/insider/<slug>', views.ticker_transactions, name='ticker_insider'),
]

stock_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stock.urls')),
    path('api/', include('stock.urls', namespace='api'), {'api': True}),
]

stock/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify


class Ticker(models.Model):
    name = models.CharField(
        verbose_name="Ticker name",
        max_length=5,
        primary_key=True,
    )

    def __str__(self):
        return self.name


class TickerPrice(models.Model):
    ticker = models.ForeignKey(
        Ticker,
        verbose_name="Ticker",
        related_name="prices",
        on_delete=models.CASCADE,
    )
    date = models.DateField(
        verbose_name="Date",
        default=timezone.now,
    )

    open_price = models.DecimalField(
        verbose_name="Open",
        max_digits=11,
        decimal_places=4,
    )
    high_price = models.DecimalField(
        verbose_name="High",
        max_digits=11,
        decimal_places=4,
    )
    low_price = models.DecimalField(
        verbose_name="Low",
        max_digits=11,
        decimal_places=4,
    )
    close_price = models.DecimalField(
        verbose_name="Close",
        max_digits=11,
        decimal_places=4,
    )

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return '{} {}'.format(self.ticker, self.date.strftime('%d.%m.%Y'))


class Insider(models.Model):
    name = models.CharField(
        verbose_name="Name",
        max_length=128,
    )
    slug = models.SlugField(unique=True, max_length=140)

    def __str__(self):
        return self.name

    def generate_unique_slug(self):
        slug = slugify(self.name)
        gen_slug = slug
        num = 1
        while Insider.objects.filter(slug=gen_slug).exists():
            gen_slug = '{}-{}'.format(slug, num)
            num += 1
        return gen_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.generate_unique_slug()
        super(Insider, self).save(*args, **kwargs)


class Transaction(models.Model):
    insider = models.ForeignKey(
        Insider,
        verbose_name="Insider",
        related_name="transactions",
        on_delete=models.CASCADE,
    )
    ticker = models.ForeignKey(
        Ticker,
        verbose_name="Ticker",
        related_name="transactions",
        on_delete=models.CASCADE,
    )

    relation = models.CharField(
        verbose_name="Relation",
        max_length=64,
    )
    last_date = models.DateField(
        verbose_name="Last Date",
        default=timezone.now,
    )
    transaction_type = models.CharField(
        verbose_name="Transaction Type",
        max_length=128,
    )

    owner_type = models.CharField(
        verbose_name="OwnerType",
        max_length=32,
    )

    shares_traded = models.PositiveIntegerField(
        verbose_name="Shares Traded",
    )
    last_price = models.DecimalField(
        verbose_name="Last Price",
        max_digits=11,
        decimal_places=4,
        null=True,
        blank=True,
    )
    shares_held = models.PositiveIntegerField(
        verbose_name="Shares Held",
        default=0,
    )

    def __str__(self):
        return '{} {} {}'.format(self.last_date, self.insider, self.transaction_type)

stock/forms.py
from django import forms

from stock.models import TickerPrice


class AnalyticsForm(forms.Form):
    date_from = forms.DateField(
        label='с',
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off',
                'class': 'datepicker',
            }
        )
    )
    date_to = forms.DateField(
        label='до',
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off',
                'class': 'datepicker',
            }
        )
    )


class DeltaForm(forms.Form):
    value = forms.IntegerField(
        label='Значение',
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off',
            }
        )
    )
    price_types = [
        ('open', 'Цена открытия'),
        ('close', 'Цена закрытия'),
        ('high', 'Максимум'),
        ('low', 'Минимум'),
    ]
    type = forms.ChoiceField(label='Тип цены', choices=price_types)

    def __init__(self, *args, **kwargs):
        super(DeltaForm, self).__init__(*args, **kwargs)

stock/views.py
from django.db import connection
from django.http import JsonResponse
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView

from stock.models import Ticker
from stock.forms import AnalyticsForm, DeltaForm

from dateutil.relativedelta import relativedelta


class TickerList(ListView):
    model = Ticker
    ordering = 'pk'
    context_object_name = 'tickers'


def ticker_prices(request, ticker_pk, api=False):
    ticker = get_object_or_404(Ticker, pk=ticker_pk)
    need_date = timezone.now() - relativedelta(months=3)
    ticker_prices = ticker.prices.filter(date__gt=need_date)
    context = {}
    if api:
        context['ticker'] = ticker.pk
        context['ticker_prices'] = list(ticker_prices.values())
        return JsonResponse(context)
    context['ticker'] = ticker
    context['ticker_prices'] = ticker_prices
    context['analytics_form'] = AnalyticsForm()
    context['delta_form'] = DeltaForm()
    return render(request, 'stock/ticker_prices.html', context)


def ticker_transactions(request, ticker_pk, api=False, *args, **kwargs):
    ticker = get_object_or_404(Ticker, pk=ticker_pk)
    ticker_transactions = ticker.transactions.filter(insider__slug=kwargs['slug']) if 'slug' in kwargs else ticker.transactions.all()
    context = {}
    if api:
        context['ticker'] = ticker.pk
        context['ticker_transactions'] = list(ticker_transactions.values(
            'insider__name',
            'relation',
            'last_date',
            'transaction_type',
            'owner_type',
            'shares_traded',
            'last_price',
            'shares_held',
        ))
        return JsonResponse(context)
    if 'slug' in kwargs:
        context['is_insider_transactions'] = True
    context['ticker'] = ticker
    context['ticker_transactions'] = ticker_transactions
    return render(request, 'stock/ticker_transactions.html', context)


def ticker_analitycs(request, ticker_pk, api=False):
    ticker = get_object_or_404(Ticker, pk=ticker_pk)
    date_from = request.GET.get('date_from')
    date_to = request.GET.get('date_to')
    context = {
        'date_from': date_from,
        'date_to': date_to,
    }
    if not (date_from and date_to):
        return render(request, 'stock/ticker_analytics.html', context)
    start_date = ticker.prices.filter(date__lte=date_from).order_by('-date').first()
    end_date = ticker.prices.filter(date__lte=date_to).order_by('-date').first()
    if start_date and end_date:
        context['diff_open_price'] = start_date.open_price - end_date.open_price
        context['diff_high_price'] = start_date.high_price - end_date.high_price
        context['diff_low_price'] = start_date.low_price - end_date.low_price
        context['diff_close_price'] = start_date.close_price - end_date.close_price
    else:
        context['not_found'] = True
    if api:
        context['ticker'] = ticker.pk
        return JsonResponse(context)
    context['ticker'] = ticker
    context['form'] = AnalyticsForm(request.GET)
    return render(request, 'stock/ticker_analytics.html', context)


def ticker_delta(request, ticker_pk, api=False):
    ticker = get_object_or_404(Ticker, pk=ticker_pk)
    context = {}
    price_diff = request.GET.get('value', 1)
    price_type = request.GET.get('type')
    if price_type not in ['open', 'high', 'low', 'close']:
        context['not_found'] = True
        return JsonResponse(context) if api else render(request, 'stock/ticker_delta.html', context)
    price_type += '_price'
    s = (
        '''SELECT MAX(first_select.date) as first_date, second_date, 'Рост' FROM (
             SELECT t1.date, t1.{price_type}, MIN(t2.date) as second_date
             FROM stock_tickerprice t1
             INNER JOIN stock_tickerprice t2
             ON (t2.{price_type} >= t1.{price_type} + {price_diff})
             AND t1.date < t2.date
             AND t1.ticker_id = t2.ticker_id
             WHERE t1.ticker_id = '{ticker_id}'
             GROUP BY t1.id ORDER BY t1.date) first_select
         GROUP BY second_date
         UNION
         SELECT MAX(second_select.date) as first_date, second_date, 'Падение' FROM (
             SELECT t1.date, t1.{price_type}, MIN(t2.date) as second_date
             FROM stock_tickerprice t1
             INNER JOIN stock_tickerprice t2
             ON (t2.{price_type} <= t1.{price_type} - {price_diff})
             AND t1.date < t2.date
             AND t1.ticker_id = t2.ticker_id
             WHERE t1.ticker_id = '{ticker_id}'
             GROUP BY t1.id ORDER BY t1.date) second_select
             GROUP BY second_date ORDER BY second_date;
        '''.format(ticker_id=ticker.pk,
                   price_diff=price_diff,
                   price_type=price_type,
                   )
    )
    cursor = connection.cursor()
    cursor.execute(s)
    results = cursor.fetchall()
    if api:
        context['ticker'] = ticker.pk
        context['results'] = list(results)
        return JsonResponse(context)
    context['form'] = DeltaForm(request.GET)
    context['results'] = results
    context['ticker'] = ticker
    return render(request, 'stock/ticker_delta.html', context)

stock/templates/stock/ticker_analytics.html
{% extends 'front.html' %}

{% block page_title %}
	{{ ticker.name }}
{% endblock page_title %}

{% block head_include %}
	<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
{% endblock head_include %}

{% block page_name %}
	<div class="row">
		<div class="col-md-4">
			{{ ticker.name }}
		</div>
	</div>
	<div class="row form-row">
		<div class="col-md-12" style="text-align: right;">
			<form action="{% url 'stock:ticker_analytics' ticker.pk %}">
				{% for field in form %}
					{{ field.label }}
					{{ field }}
				{% endfor %}
				<button class="button">Анализировать</button>
			</form>
		</div>
	</div>
{% endblock page_name %}

{% block page_content %}
	<div class="row">
		<div class="col-md-12">
			Аналитика с {{ date_from }} по {{ date_to }}
		</div>
	</div>
	{% if not_found %}
		<div class="row">
			<div class="col-md-12" style="text-align: center;">
				Данные не найдены
			</div>
		</div>
	{% else %}
		<div class="row">
				<div class="col-md-3">
					Открытие
				</div>
				<div class="col-md-3">
					Максимум
				</div>
				<div class="col-md-3">
					Минимум
				</div>
				<div class="col-md-2">
					Закрытие
				</div>		
		</div>
		<div class="row">
			<div class="col-md-3">
				{{ diff_open_price }}
			</div>
			<div class="col-md-3">
				{{ diff_high_price }}
			</div>
			<div class="col-md-3">
				{{ diff_low_price }}
			</div>
			<div class="col-md-3">
				{{ diff_close_price }}
			</div>
		</div>
	{% endif %}
{% endblock page_content %}

{% block end_include %}
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
	<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
	<script>
	    $( ".datepicker" ).datetimepicker({format: "YYYY-MM-DD"});
	</script>
{% endblock end_include %}

stock/templates/stock/ticker_delta.html
{% extends 'front.html' %}

{% block page_title %}
	{{ ticker.name }}
{% endblock page_title %}

{% block head_include %}
{% endblock head_include %}

{% block page_name %}
	<div class="row">
		<div class="col-md-4">
			{{ ticker.name }}
		</div>
	</div>
	<div class="row form-row">
		<div class="col-md-12" style="text-align: right;">
			<form action="{% url 'stock:ticker_delta' ticker.pk %}">
				{% for field in form %}
					{{ field.label }}
					{{ field }}
				{% endfor %}
				<button class="button">Рассчитать</button>
			</form>
		</div>
	</div>
{% endblock page_name %}

{% block page_content %}
	{% if not_found %}
		<div class="row">
			<div class="col-md-12" style="text-align: center;">
				Данные не найдены
			</div>
		</div>
	{% else %}
		<div class="row">
			<div class="col-md-4">
				Дата начала
			</div>
			<div class="col-md-4">
				Дата окончания
			</div>
			<div class="col-md-4">
				Процесс
			</div>
		</div>
		<div class="row">
		{% for r in results %}
			<div class="col-md-4">
				{{ r.0 }}
			</div>
			<div class="col-md-4">
				{{ r.1 }}
			</div>
			<div class="col-md-4">
				{{ r.2 }}
			</div>
		{% endfor %}
		</div>
	{% endif %}
{% endblock page_content %}

{% block end_include %}
{% endblock end_include %}

stock/templates/stock/ticker_list.html
{% extends 'front.html' %}

{% block page_title %}
	Список акций
{% endblock page_title %}

{% block head_include %}
{% endblock head_include %}

{% block page_name %}
	Список акций
{% endblock page_name %}

{% block page_content %}
	<div class="row">
		{% for ticker in tickers %}
			<div class="col-md-12">
				<a href="{% url 'stock:ticker_prices' ticker.pk %}">{{ ticker.name }}</a>
			</div>
		{% endfor %}
	</div>
{% endblock page_content %}

{% block end_include %}
{% endblock end_include %}

stock/templates/stock/ticker_prices.html
{% extends 'front.html' %}

{% block page_title %}
	{{ ticker.name }}
{% endblock page_title %}

{% block head_include %}
	<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
{% endblock head_include %}

{% block page_name %}
	<div class="row">
		<div class="col-md-4">
			{{ ticker.name }}			
		</div>
		<div class="offset-md-4 col-md-4" style="overflow: hidden;">
			<a class="button" href="{% url 'stock:ticker_insider' ticker.pk %}">Данные торговли владельцев компании</a>
		</div>
	</div>
	<div class="row form-row">
		<div class="col-md-12" style="text-align: right;">
			<form action="{% url 'stock:ticker_analytics' ticker.pk %}">
				{% for field in analytics_form %}
					{{ field.label }}
					{{ field }}
				{% endfor %}
				<button class="button">Анализировать</button>
			</form>
		</div>
	</div>
	<div class="row form-row">
		<div class="col-md-12" style="text-align: right;">
			<form action="{% url 'stock:ticker_delta' ticker.pk %}">
				{% for field in delta_form %}
					{{ field.label }}
					{{ field }}
				{% endfor %}
				<button class="button">Рассчитать</button>
			</form>
		</div>
	</div>
{% endblock page_name %}

{% block page_content %}
	<div class="row table-head">
			<div class="col-md-4">
				Дата
			</div>
			<div class="col-md-2">
				Открытие
			</div>
			<div class="col-md-2">
				Максимум
			</div>
			<div class="col-md-2">
				Минимум
			</div>
			<div class="col-md-2">
				Закрытие
			</div>		
	</div>
	<div class="row">
		{% for price in ticker_prices %}
			<div class="col-md-4">
				{{ price.date }}
			</div>
			<div class="col-md-2">
				{{ price.open_price }}
			</div>
			<div class="col-md-2">
				{{ price.high_price }}
			</div>
			<div class="col-md-2">
				{{ price.low_price }}
			</div>
			<div class="col-md-2">
				{{ price.close_price }}
			</div>
		{% endfor %}
	</div>
{% endblock page_content %}

{% block end_include %}
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
	<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
	<script>
	    $( ".datepicker" ).datetimepicker({format: "YYYY-MM-DD"});
	</script>
{% endblock end_include %}

stock/templates/stock/ticker_transactions.html
{% extends 'front.html' %}

{% block page_title %}
	{{ ticker.name }}
{% endblock page_title %}

{% block head_include %}
{% endblock head_include %}

{% block page_name %}
	<div class="row">
		<div class="col-md-4">
			{{ ticker.name }}			
		</div>
		<div class="offset-md-5 col-md-3" style="overflow: hidden;">
			<a class="button" href="{% url 'stock:ticker_prices' ticker.pk %}">Цены</a>
		</div>
	</div>
{% endblock page_name %}

{% block page_content %}
	<div class="row table-head">
			<div class="col-md-2">
				Insider
			</div>
			<div class="col-md-1">
				Relation
			</div>
			<div class="col-md-2">
				Last date
			</div>
			<div class="col-md-2">
				Transaction type
			</div>
			<div class="col-md-2">
				OwnerType
			</div>
			<div class="col-md-1">
				Shares Traded
			</div>
			<div class="col-md-1">
				Last price
			</div>
			<div class="col-md-1">
				Shares Held
			</div>
	</div>
	<div class="row">
		{% for transaction in ticker_transactions %}
			<div class="col-md-2">
				{% if is_insider_transactions %}
					{{ transaction.insider }}
				{% else %}
					<a href="{% url 'stock:ticker_insider' ticker.pk transaction.insider.slug %}">
						{{ transaction.insider }}
					</a>
				{% endif %}
			</div>
			<div class="col-md-1">
				{{ transaction.relation }}
			</div>
			<div class="col-md-2">
				{{ transaction.last_date }}
			</div>
			<div class="col-md-2">
				{{ transaction.transaction_type }}
			</div>
			<div class="col-md-2">
				{{ transaction.owner_type }}
			</div>
			<div class="col-md-1">
				{{ transaction.shares_traded }}
			</div>
			<div class="col-md-1">
				{{ transaction.last_price }}
			</div>
			<div class="col-md-1">
				{{ transaction.shares_held }}
			</div>
		{% endfor %}
	</div>
{% endblock page_content %}

{% block end_include %}
{% endblock end_include %}